/** Edge TTS neural voices — server-side Microsoft Azure Neural speech */
export const KOKORO_VOICES = [
  { id: 'en-US-AvaMultilingualNeural', name: 'Ava (US Female)', grade: 'A' },
  { id: 'en-US-AndrewMultilingualNeural', name: 'Andrew (US Male)', grade: 'A' },
  { id: 'en-US-JennyNeural', name: 'Jenny (US Female)', grade: 'A' },
  { id: 'en-US-GuyNeural', name: 'Guy (US Male)', grade: 'A-' },
  { id: 'en-US-AriaNeural', name: 'Aria (US Female)', grade: 'A-' },
  { id: 'en-US-AndrewNeural', name: 'Andrew (US Male)', grade: 'A-' },
  { id: 'en-US-EmmaMultilingualNeural', name: 'Emma (US Female)', grade: 'A-' },
  { id: 'en-US-BrianMultilingualNeural', name: 'Brian (US Male)', grade: 'A-' },
  { id: 'en-US-SaraNeural', name: 'Sara (US Female)', grade: 'B+' },
  { id: 'en-US-DavisNeural', name: 'Davis (US Male)', grade: 'B+' },
  { id: 'en-US-JaneNeural', name: 'Jane (US Female)', grade: 'B' },
  { id: 'en-US-JasonNeural', name: 'Jason (US Male)', grade: 'B' },
  { id: 'en-US-TonyNeural', name: 'Tony (US Male)', grade: 'B' },
  { id: 'en-US-NancyNeural', name: 'Nancy (US Female)', grade: 'B' },
  { id: 'en-GB-SoniaNeural', name: 'Sonia (British Female)', grade: 'A-' },
  { id: 'en-GB-RyanNeural', name: 'Ryan (British Male)', grade: 'B+' },
  { id: 'en-GB-LibbyNeural', name: 'Libby (British Female)', grade: 'B' },
  { id: 'en-AU-NatashaNeural', name: 'Natasha (Australian Female)', grade: 'B+' },
  { id: 'en-AU-WilliamNeural', name: 'William (Australian Male)', grade: 'B+' },
  { id: 'en-IN-NeerjaNeural', name: 'Neerja (Indian Female)', grade: 'B' },
  { id: 'en-IN-PrabhatNeural', name: 'Prabhat (Indian Male)', grade: 'B' },
];
