/** Kokoro voice IDs - used when TTS engine is kokoro (backend) */
export const KOKORO_VOICES = [
  { id: 'af_heart', name: 'Heart (Female)', grade: 'A' },
  { id: 'af_bella', name: 'Bella (Female)', grade: 'A-' },
  { id: 'af_nicole', name: 'Nicole (Female)', grade: 'B-' },
  { id: 'bf_emma', name: 'Emma (British Female)', grade: 'B-' },
  { id: 'af_sarah', name: 'Sarah (Female)', grade: 'C+' },
  { id: 'af_kore', name: 'Kore (Female)', grade: 'C+' },
  { id: 'af_aoede', name: 'Aoede (Female)', grade: 'C+' },
  { id: 'am_fenrir', name: 'Fenrir (Male)', grade: 'C+' },
  { id: 'am_michael', name: 'Michael (Male)', grade: 'C+' },
  { id: 'am_puck', name: 'Puck (Male)', grade: 'C+' },
  { id: 'bf_isabella', name: 'Isabella (British Female)', grade: 'C' },
  { id: 'bm_george', name: 'George (British Male)', grade: 'C' },
  { id: 'bm_fable', name: 'Fable (British Male)', grade: 'C' },
  { id: 'af_alloy', name: 'Alloy (Female)', grade: 'C' },
  { id: 'af_nova', name: 'Nova (Female)', grade: 'C' },
  { id: 'af_sky', name: 'Sky (Female)', grade: 'C-' },
  { id: 'am_echo', name: 'Echo (Male)', grade: 'D' },
  { id: 'am_eric', name: 'Eric (Male)', grade: 'D' },
  { id: 'am_liam', name: 'Liam (Male)', grade: 'D' },
  { id: 'am_onyx', name: 'Onyx (Male)', grade: 'D' },
  { id: 'af_river', name: 'River (Female)', grade: 'D' },
  { id: 'af_jessica', name: 'Jessica (Female)', grade: 'D' },
  { id: 'bf_alice', name: 'Alice (British Female)', grade: 'D' },
  { id: 'bf_lily', name: 'Lily (British Female)', grade: 'D' },
  { id: 'bm_daniel', name: 'Daniel (British Male)', grade: 'D' },
  { id: 'bm_lewis', name: 'Lewis (British Male)', grade: 'D+' },
];
