services:
  - type: web
    name: audire-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node --max-old-space-size=400 index.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        sync: false
